### ISSUE TITLE
Tweaks to collapsable components and helpers

### ISSUE THREAD

**Issue by knownasilya** [glimmerjs/glimmer-playground#15]
Related to #14 

Just a couple things I noticed

- Clicking the arrow twice selects the text of that component. Maybe using user-select: none?
- Would be nice to click the whole header, not just the tiny icon

**Comment by nummi** [comment]
> user-select: none

👍 

> Would be nice to click the whole header, not just the tiny icon

I decided against this because there can be a lot of interaction on the left side of the header (edit component/helper name, remove file, confirm/cancel removal). But I did give the clickable area some padding:

<img width="91" alt="screen shot 2018-01-13 at 7 24 46 am" src="https://user-images.githubusercontent.com/3692/34907419-054c3ab4-f833-11e7-8f8e-9375cb82d23b.png">

**Comment by knownasilya** [comment]
> I decided against this because there can be a lot of interaction on the left side of the header (edit component/helper name, remove file, confirm/cancel removal).

👍

**Comment by tomdale** [comment]
I think this can be closed now that #16 is merged?

**Comment by nummi** [comment]
@tomdale :+1:
